name: Release
on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      new_tag_version: ${{ steps.tag_version.outputs.new_tag_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Dry run to get the next release version
        id: tag_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export NEXT_TAG_VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed -E 's/.* ([[:alnum:].\-]+)$/\1/')
          echo "new_tag_version=${NEXT_TAG_VERSION}" >> $GITHUB_OUTPUT
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  docker:
    needs: release
    if: ${{ needs.release.outputs.new_tag_version != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        env:
          DOCKER_IMAGE_TAG: ${{ needs.release.outputs.new_tag_version }}
        run: docker build -t ghcr.io/truzzt/ids-basecamp-daps:$DOCKER_IMAGE_TAG .

      - name: Push Docker image
        env:
          DOCKER_IMAGE_TAG: ${{ needs.release.outputs.new_tag_version }}
        run: docker push ghcr.io/truzzt/ids-basecamp-daps:$DOCKER_IMAGE_TAG

  helm:
    needs: release
    if: ${{ needs.release.outputs.new_tag_version != '' }}
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'helm-chart/Chart.yaml'
          propertyPath: 'file.version'
          value: ${{ needs.release.outputs.new_tag_version }}
          commitChange: true

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: ./helm-chart
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
